### ISSUE TITLE
doesnt work

### ISSUE THREAD

**Issue by AlexViBrittannia** [G3NSVRV/OperaGXMods#3]
I was using it for months and now it uninstalled itself, when I try to reinstall it I get a package error and it doesn't install
![Captura](https://github.com/G3NSVRV/OperaGXMods/assets/150694847/5dee67f2-6c9e-4cfb-9013-eed26d27b57e)

**Comment by g3nsvrv** [comment]
Duplicated

https://github.com/G3NSVRV/OperaGXMods/issues/2
